# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_test',
            name='redirection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_test_r', to='my_app.Page'),
        ),
    ]
