# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_page_redirection_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_connection',
            name='page_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_connection_1', to='my_app.Page'),
        ),
        migrations.AlterField(
            model_name='page_connection',
            name='page_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_connection_2', to='my_app.Page'),
        ),
        migrations.AlterField(
            model_name='page_test',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_test_p', to='my_app.Page'),
        ),
        migrations.AlterField(
            model_name='page_test',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_test_t', to='my_app.Test'),
        ),
        migrations.AlterField(
            model_name='t_p_b',
            name='button',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_p_b_b', to='my_app.Button'),
        ),
        migrations.AlterField(
            model_name='t_p_b',
            name='page_test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_t_b_pt', to='my_app.Page_Test'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ipv4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
