# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20170513_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_p', to='my_app.Page'),
        ),
    ]
