# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20170515_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='avg_download_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
