# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20170516_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='address',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='cookies_present',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='encoding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='force_test',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page_host',
            name='domain_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='page_host',
            name='ipv4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='page_test',
            name='download_time',
            field=models.IntegerField(blank=True, null=True, verbose_name=2000),
        ),
        migrations.AlterField(
            model_name='page_test',
            name='is_working',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page_test',
            name='response_code',
            field=models.IntegerField(blank=True, null=True, verbose_name=1000),
        ),
        migrations.AlterField(
            model_name='t_p_b',
            name='is_working',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mac_address',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='transfer_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
